name: "lint"

permissions:
  actions: "write"
  contents: "read"
  discussions: "write"
  pull-requests: "write"

on:
  pull_request:
    types: ["opened", "reopened"]
  push:
  schedule:
    # Run at midnight UTC every day with 15 minutes delay added to avoid high load periods
    - cron: "15 0 * * *"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  lint-check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"
      - uses: "actions/setup-node@v4"
        with:
          node-version: 22
      - run: "npm --prefix new-log-viewer/ clean-install"
      - uses: "CatChen/eslint-suggestion-action@v4"
        with:
          config-path: "./package.json"
          directory: "./new-log-viewer"
          fail-check: true
          request-changes: true
          targets: "./src/**/*.{js,jsx,ts,tsx}"
